spring.application.name=os

#----  h2 settings ---- #

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:agilexpert_db
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true



